""" Main script that works as a dispatcher in code ocean """

import json
import logging
import os
import re
import sys
import time
from glob import glob
from pathlib import Path
from typing import List, Tuple, Union

import yaml
from aind_codeocean_api.codeocean import CodeOceanClient
from aind_codeocean_api.models.data_assets_requests import (
    CreateDataAssetRequest, Source, Sources)
from ng_link import NgState
from utils import utils
from _init_ import __pipeline_version__, __maintainers__, __pipeline_notes__

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s : %(message)s",
    datefmt="%Y-%m-%d %H:%M",
    handlers=[
        logging.StreamHandler(),
        # logging.FileHandler("test.log", "a"),
    ],
)
logging.disable("DEBUG")
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

PathLike = Union[str, Path]

SCRIPT_DIR = Path(os.path.abspath(__file__)).parent

def wavelength_to_hex(wavelength: int) -> int:
    """
    Converts wavelength to corresponding color hex value.

    Parameters
    ------------------------
    wavelength: int
        Integer value representing wavelength.

    Returns
    ------------------------
    int:
        Hex value color.
    """
    # Each wavelength key is the upper bound to a wavelgnth band.
    # Wavelengths range from 380-750nm.
    # Color map wavelength/hex pairs are generated by sampling
    # along a CIE diagram arc.

    color_map = {
        460: 0x690AFE,  # Purple
        470: 0x3F2EFE,  # Blue-Purple
        480: 0x4B90FE,  # Blue
        490: 0x59D5F8,  # Blue-Green
        500: 0x5DF8D6,  # Green
        520: 0x5AFEB8,  # Green
        540: 0x58FEA1,  # Green
        560: 0x51FF1E,  # Green
        565: 0xBBFB01,  # Green-Yellow
        575: 0xE9EC02,  # Yellow
        580: 0xF5C503,  # Yellow-Orange
        590: 0xF39107,  # Orange
        600: 0xF15211,  # Orange-Red
        620: 0xF0121E,  # Red
        750: 0xF00050,
    }  # Pink

    for ub, hex_val in color_map.items():
        if wavelength < ub:  # Exclusive
            return hex_val
    return hex_val  # hex_val is set to the last color in for loop


def wavelength_to_hex_alternate(wavelength: int) -> int:
    """
    Converts wavelengths to hex value, taking fpbase.org spectra viewer
    as a guide.
    Fluorescent proteins querried:
    mTFP1,
    EGFP,
    SYFP2,
    mbanana,
    morange,
    mtomato,
    mcherry,
    mraspberry,
    mplum

    Parameters
    ------------------------
    wavelength: int
        Integer value representing wavelength.

    Returns
    ------------------------
    int:
        Hex value color.
    """

    color_map = {
        500: 0x61ABFD,  # RUDDY BLUE, mTFP/mTurquoise
        530: 0x92FF42,  # CHARTREUSE,   EGFP
        540: 0xE4FE41,  # CHARTREUSE, SYFP2
        560: 0xF3D038,  # MUSTARD, mBanana
        580: 0xEAB032,  # XANTHOUS, mOrange
        600: 0xF15F22,  # GIANTS ORANGE, tdTomato/mScarlet
        630: 0xED1C24,  # RED, mCherry
        680: 0xC51E1F,  # FIRE ENGINE RED, mRaspberry
        700: 0xA81F1F,  # FIRE BRICK, mPlum
    }

    for ub, hex_val in color_map.items():
        if wavelength <= ub:  # Inclusive
            return hex_val
    return hex_val  # hex_val is set to the last color in for loop


def get_yaml_config(filename):
    """
    Get default configuration from a YAML file.
    Parameters
    ------------------------
    filename: str
        String where the YAML file is located.
    Returns
    ------------------------
    Dict
        Dictionary with the configuration
    """

    with open(filename, "r") as stream:
        config = yaml.safe_load(stream)

    return config


def wait_for_data_availability(
    co_client,
    data_asset_id: str,
    timeout_seconds: int = 300,
    pause_interval=10,
):
    """
    There is a lag between when a register data request is made and when the
    data is available to be used in a capsule.
    Parameters
    ----------
    data_asset_id : str
    timeout_seconds : int
        Roughly how long the method should check if the data is available.
    pause_interval : int
        How many seconds between when the backend is queried.

    Returns
    -------
    requests.Response

    """
    num_of_checks = 0
    break_flag = False
    time.sleep(pause_interval)
    response = co_client.get_data_asset(data_asset_id)

    if ((pause_interval * num_of_checks) > timeout_seconds) or (
        response.status_code == 200
    ):
        break_flag = True
    while not break_flag:
        time.sleep(pause_interval)
        response = co_client.get_data_asset(data_asset_id)
        num_of_checks += 1
        if ((pause_interval * num_of_checks) > timeout_seconds) or (
            response.status_code == 200
        ):
            break_flag = True
    return response


def make_data_viewable(co_client: CodeOceanClient, response_contents: dict):
    """
    Makes a registered dataset viewable

    Parameters
    ----------
    co_client: CodeOceanClient
        Code ocean client

    response_contents: dict
        Dictionary with the response
        of the created data asset

    """
    data_asset_id = response_contents["id"]
    response_data_available = wait_for_data_availability(co_client, data_asset_id)

    if response_data_available.status_code != 200:
        logger.info(f"Unable to find: {data_asset_id}")
        return

    # Make data asset viewable to everyone
    update_data_perm_response = co_client.update_permissions(
        data_asset_id=data_asset_id, everyone="viewer"
    )
    logger.info(f"Data asset viewable to everyone: {update_data_perm_response}")


def dispatch(
    processing_manifest: dict,
    results_folder: PathLike,
    bucket: str,
    co_domain: str = "https://codeocean.allenneuraldynamics.org",
):
    """
    Creates multiple processing manifest jsons using
    the original processing manifest. This is done to
    use the flatten connection and instantiate multiple
    computations to process each channel in parallel.

    Parameters
    ----------
    processing_manifest: dict
        Dictionary with the processing manifest
        metadata

    results_folder: str
        Path pointing to the results folder

    bucket: str
        Bucket name where the data is stored

    co_domain: str
        Code Ocean domain
    """

    logger.info(f"Provided processing manifest: {processing_manifest}")

    codeocean_domain = co_domain  # os.getenv("API_KEY")
    co_token = os.getenv("API_SECRET")
    co_client = CodeOceanClient(domain=codeocean_domain, token=co_token)

    # Getting path in S3
    dataset_to_register = processing_manifest["pipeline_processing"]["stitching"][
        "s3_path"
    ]

    pattern = (
        r"SmartSPIM_\d+_\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}"
        r"_stitched_\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}"
    )
    found_pattern = re.findall(pattern=pattern, string=dataset_to_register)

    # Extract the data asset info
    if len(found_pattern):
        dataset_to_register = found_pattern[0]

        smartspim_fused_tags = ["smartspim", "processed"]

        # Registering AWS data asset
        aws_source = Sources.AWS(
            bucket=bucket,
            prefix=dataset_to_register,
            keep_on_external_storage=True,
            public=True,
        )
        source = Source(aws=aws_source)

        create_data_asset_request = CreateDataAssetRequest(
            name=dataset_to_register,
            tags=smartspim_fused_tags,
            mount=dataset_to_register,
            source=source,
            custom_metadata=None,
        )

        input_json_data = json.loads(create_data_asset_request.json_string)

        # Register the fused smartspim dataset
        try:
            data_asset_reg_response = co_client.create_data_asset(
                request=input_json_data
            )

            response_contents = data_asset_reg_response.json()
            logger.info(f"Created data asset in Code Ocean: {response_contents}")

            # Making the created data asset available for everyone
            make_data_viewable(co_client, response_contents)

        except Exception as e:
            logger.warning(f"Error registering data asset in the API call. Error: {e}")

    else:
        logger.warning("Error registering data asset")

    logger.info(f"Processing manifest: {processing_manifest}")

    # Creating processing manifests for channels to register
    pipeline_config = processing_manifest.get("pipeline_processing")

    if pipeline_config:
        logger.info("Creating segmentation and quantification parameters")
        # Creating processing manifests for channels to segment and quantify
        segment_channels = pipeline_config["segmentation"]["channels"]
        background_channel = processing_manifest["pipeline_processing"]["registration"][
            "channels"
        ][0]

        if len(segment_channels):
            print(f"Preparing segmentation configs for: {segment_channels}")

            for channel_to_segment in segment_channels:
                copy_pipeline_config = pipeline_config.copy()

                copy_pipeline_config["segmentation"]["input_data"] = "../data/fused"
                copy_pipeline_config["segmentation"]["channel"] = channel_to_segment
                copy_pipeline_config["segmentation"][
                    "background_channel"
                ] = background_channel

                # Creating quantification parameters
                copy_pipeline_config["quantification"] = {}
                copy_pipeline_config["quantification"]["fused_folder"] = "../data/fused"
                copy_pipeline_config["quantification"]["channel"] = channel_to_segment
                copy_pipeline_config["quantification"]["save_path"] = "../results/"

                utils.save_dict_as_json(
                    f"{results_folder}/segmentation_processing_manifest_{channel_to_segment}.json",
                    copy_pipeline_config,
                )

        else:
            utils.save_dict_as_json(
                f"{results_folder}/segmentation_processing_manifest_empty.json",
                pipeline_config.copy(),
            )
            
            print(f"No segmentation channels provided, pipeline config: {pipeline_config}")

    else:
        raise BaseException("Stopping pipeline, pipeline configuration.")


def clean_up(
    processing_manifest: dict,
    data_folder: PathLike,
    results_folder: PathLike,
    alert_bot_link: str,
):
    """
    Moves all the data to the aind-open-data bucket in
    AWS.

    Parameters
    ----------
    processing_manifest: dict
        Dictionary with the processing manifest
        metadata

    data_folder: str
        Path pointing to the data folder

    results_folder: str
        Path pointing to the results folder

    bucket: str
        Bucket name

    alert_bot_link: str
        Link to Team's channel for SmartSPIM notifications
    """
    logger.info(f"Data folder: {os.listdir(data_folder)}")

    # # Variables from processing manifest
    # bucket = "aind-open-data"

    cell_folders = glob(f"{data_folder}/cell_*")
    quantification_folders = glob(f"{data_folder}/quant_*")

    logger.info(f"Cell folders: {cell_folders}")
    logger.info(f"Quantification folders: {quantification_folders}")

    # Reading proposals processings
    proposals_processing = []
    for cell_folder in cell_folders:
        processing_jsons = [
            p
            for p in glob(f"{cell_folder}/proposals/metadata/*processing*.json")
            if "manifest" not in str(p)
        ]
        proposals_processing.append(processing_jsons)

    # Reading segmentation processings
    segmentation_processing = []
    for cell_folder in cell_folders:
        processing_jsons = [
            p
            for p in glob(f"{cell_folder}/metadata/*processing*.json")
            if "manifest" not in str(p)
        ]
        segmentation_processing.append(processing_jsons)

    # Reading quantification processings
    quantification_processing = []
    for quant_folder in quantification_folders:
        processing_jsons = [
            p
            for p in glob(f"{quant_folder}/metadata/*processing*.json")
            if "manifest" not in str(p)
        ]
        quantification_processing.append(processing_jsons)

    # Building from previous processing json
    processing_paths = list()
    combined_processing_list = (
        [[f"{data_folder}/input_aind_metadata/processing.json"]]
        + proposals_processing
        + segmentation_processing
        + quantification_processing
    )
    for sub_list in combined_processing_list:
        processing_paths += sub_list

    logger.info(f"Compiling processing paths: {processing_paths}")
    
    if len(processing_paths) > 1:
        output_filename = utils.compile_processing_jsons(
            processing_paths=processing_paths,
            output_general_processing=results_folder,
            processor_full_name=__maintainers__[0],
            pipeline_version=__pipeline_version__,
            pipeline_notes=__pipeline_notes__,
        )

        logger.info(f"Compiled processing.json in path {output_filename}")

        # Moving data out
        # Defining s3 outputs
        s3_path = processing_manifest["pipeline_processing"]["stitching"]["s3_path"]
        cell_s3_output = f"{s3_path}/image_cell_segmentation"
        quantification_s3_output = f"{s3_path}/image_cell_quantification"

        regex_channels = r"Ex_(\d{3})_Em_(\d{3})$"

        # Copying final processing manifest
        for out in utils.execute_command_helper(
            f"aws s3 cp {output_filename}/processing.json {s3_path}/processing.json"
        ):
            print(out)

        # Moving data to the cell folder
        for cell_folder in cell_folders:
            channel_name = re.search(regex_channels, cell_folder).group()

            for out in utils.execute_command_helper(
                f"aws s3 mv --recursive {cell_folder} {cell_s3_output}/{channel_name}"
            ):
                print(out)

        # Moving data to the quantification folder
        for quantification_folder in quantification_folders:
            channel_name = re.search(regex_channels, quantification_folder).group()

            for out in utils.execute_command_helper(
                f"aws s3 mv --recursive {quantification_folder} {quantification_s3_output}/{channel_name}"
            ):
                print(out)

        utils.save_string_to_txt(
            f"Results of cell segmentation saved in: {cell_s3_output}",
            f"{results_folder}/output_cell.txt",
        )

        utils.save_string_to_txt(
            f"Results of quantification saved in: {quantification_s3_output}",
            f"{results_folder}/output_quantification.txt",
        )
    
    else:
        print("No segmentation data to copy!")
        utils.save_dict_as_json(
            filename=f"{results_folder}/processing_manifest_no_cell_detection.json",
            dictionary=processing_manifest,
        )

    alert_bot = utils.AlertBot(url=alert_bot_link)
    alert_bot.send_message(
        f"Finished processing dataset: {processing_manifest['name']}"
    )


def get_data_config(
    data_folder: PathLike,
    processing_manifest_path: str = "processing_manifest.json",
    data_description_path: str = "data_description.json",
) -> Tuple:
    """
    Returns the first smartspim dataset found
    in the data folder

    Parameters
    -----------
    data_folder: str
        Path to the folder that contains the data

    processing_manifest_path: str
        Path for the processing manifest

    data_description_path: str
        Path for the data description

    Returns
    -----------
    Tuple[Dict, str, list]
        Dict: Empty dictionary if the path does not exist,
        dictionary with the data otherwise.

        Str: Empty string if the processing manifest
        was not found

        List: Empty list if no investigators in data description
    """

    # Returning first smartspim dataset found
    # Doing this because of Code Ocean, ideally we would have
    # a single dataset in the pipeline

    processing_manifest_path = Path(f"{data_folder}/{processing_manifest_path}")
    data_description_path = Path(f"{data_folder}/{data_description_path}")

    if not processing_manifest_path.exists():
        raise ValueError(
            f"Please, check processing manifest path: {processing_manifest_path}"
        )

    if not data_description_path.exists():
        raise ValueError(
            f"Please, check data description path: {data_description_path}"
        )

    derivatives_dict = utils.read_json_as_dict(str(processing_manifest_path))
    data_description_dict = utils.read_json_as_dict(str(data_description_path))

    smartspim_dataset = data_description_dict.get("name")
    investigators = data_description_dict.get("investigators")

    return derivatives_dict, smartspim_dataset, investigators


def copy_intermediate_data(
    output_dispatch_metadata: PathLike,
    flatfield_folder: List[PathLike],
    destripe_files: List[PathLike],
    stitch_folder: List[PathLike],
    fuse_folder: List[PathLike],
    ccf_folders: List[PathLike],
    s3_path: str,
    results_folder: PathLike,
    logger: logging.Logger,
):
    """
    Copies the destripe, stitch and fusion metadata
    to the destination bucket to make it available
    to scientists as soon as possible.

    Parameters
    ----------
    output_dispatch_metadata: PathLike
        Path where the new metadata (derived)
        for the processed dataset is located

    destripe_files: List[PathLike]
        Metadata files generated in the
        parallel destriping step

    flatfield_channels: List[PathLike]
        Flatfields applied to the dataset

    stitch_folders: List[PathLike]
        Stitch folders generated in the
        stitch step.

    fuse_folders: List[PathLike]
        Fuse folders generated in the
        parallel fusion step.

    ccf_folders: List[PathLike]
        CCF registration folders generated
        in the pipeline.

    s3_path: str
        Path where we want to copy the data to s3.

    results_folder: PathLike
        Results folder path in Code Ocean

    logger: logging.Logger
        Logging object

    """
    flatfield_processings = [str(flatfield_folder.joinpath("metadata/processing.json"))]
    stitch_processings = [str(stitch_folder.joinpath("metadata/processing.json"))]
    fuse_processings = [str(p) for p in list(fuse_folder.glob("*_processing.json"))]
    ccf_processings = []

    for ccf_folder in ccf_folders:
        processing_jsons = [
            p
            for p in glob(f"{ccf_folder}/metadata/*processing*.json")
            if "manifest" not in str(p)
        ]
        ccf_processings.append(processing_jsons)

    # Flattening list
    processing_paths = list()
    combined_processing_list = ccf_processings
    for sub_list in combined_processing_list:
        processing_paths += sub_list

    processing_paths = (
        flatfield_processings
        + destripe_files
        + stitch_processings
        + fuse_processings
        + processing_paths
    )
    logger.info(f"Processing paths: {processing_paths}")

    try:
        output_filename = utils.compile_processing_jsons(
            processing_paths=processing_paths,
            output_general_processing=output_dispatch_metadata,
            processor_full_name=__maintainers__[0],
            pipeline_version=__pipeline_version__,
            pipeline_notes=__pipeline_notes__,
        )

    except Exception as e:
        print(f"Error while compiling processing manifests: {e}")
        output_filename = None

    logger.info(f"Compiled processing.json in path {output_filename}")

    # Copying derived metadata
    output_dispatch_metadata = Path(output_dispatch_metadata)
    for out in utils.execute_command_helper(
        f"aws s3 cp --recursive {output_dispatch_metadata} {s3_path}"
    ):
        logger.info(out)

    # Copying out fused data
    output_fusion = "image_tile_fusing"
    dest_metadata_path = f"{s3_path}/{output_fusion}/metadata"
    dest_zarr_path = f"{s3_path}/{output_fusion}/OMEZarr"

    cmd = f"aws s3 cp --recursive {flatfield_folder} {dest_metadata_path}/flatfield_correction"

    logger.info(f"Executing CMD: {cmd}")

    for out in utils.execute_command_helper(cmd):
        logger.info(out)

    for fused_zarr in fuse_folder.glob("*.zarr"):
        fused_zarr_file_path = str(fused_zarr)
        fused_zarr_filename = str(fused_zarr.name)

        logger.info(
            f"Copying data from {fused_zarr_file_path} to {dest_zarr_path}/{fused_zarr_filename}"
        )

        cmd = f"aws s3 cp --recursive {fused_zarr_file_path} {dest_zarr_path}/{fused_zarr_filename}"

        logger.info(f"Executing CMD: {cmd}")

        for out in utils.execute_command_helper(cmd):
            logger.info(out)

    fused_metadata_files = list(fuse_folder.glob("*.yaml")) + list(
        fuse_folder.glob("*.json")
    )
    for fused_metadata in fused_metadata_files:
        fused_mdata_file_path = str(fused_metadata)
        fused_mdata_filename = str(fused_metadata.name)

        logger.info(
            f"Copying data from {fused_mdata_file_path} to {dest_metadata_path}/fuse/{fused_mdata_filename}"
        )

        cmd = f"aws s3 cp {fused_mdata_file_path} {dest_metadata_path}/fusion/{fused_mdata_filename}"
        logger.info(f"Executing CMD: {cmd}")

        for out in utils.execute_command_helper(cmd):
            logger.info(out)

    logger.info(f"Copying data from {stitch_folder} to {dest_metadata_path}/stitching")

    cmd = f"aws s3 cp --recursive {stitch_folder} {dest_metadata_path}/stitching"
    logger.info(f"Executing CMD: {cmd}")

    for out in utils.execute_command_helper(cmd):
        logger.info(out)

    # Copying ccf data
    ccf_s3_output = f"{s3_path}/image_atlas_alignment"
    regex_channels = r"Ex_(\d{3})_Em_(\d{3})$"

    for ccf_folder in ccf_folders:
        channel_name = re.search(regex_channels, ccf_folder).group()

        for out in utils.execute_command_helper(
            f"aws s3 mv --recursive {ccf_folder} {ccf_s3_output}/{channel_name}"
        ):
            logger.info(out)

    utils.save_string_to_txt(
        f"Stitched dataset saved in: {s3_path}",
        f"{results_folder}/output_stitching.txt",
    )


def create_derived_stitched_metadata(
    data_folder: PathLike, results_folder: PathLike, logger: logging.Logger
) -> Tuple[PathLike, str]:
    """
    Creates the derived metadata following
    AIND conventions.

    Parameters
    ----------
    data_folder: PathLike
        Path to the code ocean data folder

    results_folder: PathLike
        Path to the code ocean results folder

    logger: logging.Logger
        Logging object

    Returns
    -------
    Tuple[PathLike, str]
        The first position of the tuple
        corresponds to the path where the
        metadata was created while the
        second position has the new name
        of the dataset
    """
    logger.info("Generating derived data description")
    raw_metadata_path = data_folder.joinpath("input_aind_metadata")
    output_dispatch_metadata = f"{results_folder}/output_aind_metadata"
    utils.create_folder(output_dispatch_metadata)

    new_dataset_name = utils.generate_data_description(
        raw_data_description_path=raw_metadata_path.joinpath("data_description.json"),
        dest_data_description=output_dispatch_metadata,
        process_name="stitched",
    )

    logger.info("Copying all available raw SmartSPIM metadata")

    # This is the AIND metadata
    found_metadata = utils.copy_available_metadata(
        input_path=raw_metadata_path,
        output_path=output_dispatch_metadata,
        files_to_copy=[
            "acquisition.json",
            "instrument.json",
            "subject.json",
            "procedures.json",
            "session.json",
        ],
    )

    logger.info(f"Copied metadata from {raw_metadata_path}: {found_metadata}")
    logger.info(
        f"Metadata in raw folder {raw_metadata_path}: {os.listdir(raw_metadata_path)}"
    )
    logger.info(
        f"Metadata in folder {output_dispatch_metadata}: {os.listdir(output_dispatch_metadata)}"
    )

    return output_dispatch_metadata, new_dataset_name


def create_ng_link(
    config: dict, s3_channel_paths: List[str], s3_dataset_path: str
) -> str:
    """
    Creates the neuroglancer link for the processed dataset

    Parameters
    -------------

    config: dict
        Image configuration necessary to build the
        neuroglancer link

    s3_channel_paths: List[str]
        S3 paths for each of the channels

    s3_dataset_path: str
        S3 path where the dataset is stored

    Returns
    -------------
    Tuple[str, str]
        str:
            Path where the neuroglancer config json
            was generated
        str:
            Neuroglancer link path
    """
    # Sort channels paths so that they appear in NG consistently ordered
    s3_channel_paths = sorted(s3_channel_paths)

    dimensions = {
        "z": {
            "voxel_size": config["z_res"],
            "unit": "microns",
        },
        "y": {
            "voxel_size": config["y_res"],
            "unit": "microns",
        },
        "x": {
            "voxel_size": config["x_res"],
            "unit": "microns",
        },
        "t": {"voxel_size": 0.001, "unit": "seconds"},
    }

    colors = []
    for channel_str in s3_channel_paths:
        channel_str = str(Path(channel_str).stem).replace(".ome", "")
        channel: int = int(channel_str.split("_")[-1])
        hex_val: int = wavelength_to_hex_alternate(channel)
        hex_str = f"#{str(hex(hex_val))[2:]}"

        colors.append(hex_str)

    # Creating layer per channel
    layers = []
    for idx in range(len(s3_channel_paths)):
        channel_name = Path(s3_channel_paths[idx]).name

        layers.append(
            {
                "source": s3_channel_paths[idx],
                "type": "image",
                # use channel idx when source is the same
                # in zarr to change channel otherwise 0
                "channel": 0,
                "name": channel_name,
                "opacity": 1,
                "blend": "additive",
                "tab": "rendering",
                "shader": {
                    "color": colors[idx],
                    "emitter": "RGB",
                    "vec": "vec3",
                },
                "shaderControls": {"normalized": {"range": [0, 200]}},  # Optional
            }
        )

    subject_id = Path(s3_dataset_path).name.split("_")[1]
    input_configs = {
        "title": subject_id,
        "dimensions": dimensions,
        "layers": layers,
        "crossSectionOrientation": [0.5, 0.5, 0.5, -0.5],
        "crossSectionScale": 15,
    }

    neuroglancer_link = NgState(
        input_config=input_configs,
        mount_service="s3",
        bucket_path=config["bucket_path"],
        output_dir=config["output_folder"],
        base_url=config["ng_base_url"],
        json_name="neuroglancer_config.json",
    )

    ng_link = f"{config['ng_base_url']}#!{s3_dataset_path}/neuroglancer_config.json"
    # Modifying output path in s3 for when the data is moved
    json_state = neuroglancer_link.state
    json_state["ng_link"] = ng_link

    ng_output_path = f"{config['output_folder']}/neuroglancer_config.json"

    with open(ng_output_path, "w") as outfile:
        json.dump(json_state, outfile, indent=2)

    return Path(ng_output_path), ng_link


def send_email_alerts(
    mode: str,
    alert_configs: dict,
    investigators: list,
    dataset_name: str,
    logger: logging.Logger,
    email_message_params: dict = {},
    source_email: str = "notifications@allenneuraldynamics.org",
):
    """
    Checks if there is investigator info and sends email

    Parameters
    ----------
    mode : str
        The current mode of the dispatcher
    alert_configs : dict
        Information on accessing investigator email list
    investigators : list
        investigators that submitted the dataset
    dataset_name : str
        current dataset being processed
    logger : logging.Logger
        logger object
    source_email: str
        Source email.
        Default: notifications@allenneuraldynamics.org

    """

    if len(investigators) and len(investigators[0]):
        # Parsing investigators name from PIDName
        investigators = [
            inv["name"] if isinstance(inv, dict) else inv for inv in investigators
        ]
        response = utils.send_ses_alerts(
            mode=mode,
            alert_configs=alert_configs,
            investigators=investigators,
            dataset=dataset_name,
            email_message_params=email_message_params,
            source_email=source_email,
        )
        logger.info(
            f"Email alert response: {response} - Investigators: {investigators}"
        )

    else:
        logger.info("Email not sent: No investigators were provided")


def run():
    """
    Run function allows the smartspim pipeline to execute
    in parallel. It receives an input parameter related to
    the capsule mode:

    - "dispatch": This mode dispatches multiple instances of
    the downstream capsules.

    - "clean": This mode cleans up all the results from the
    downstream capsules because our data is being copied to the
    aind-open-data bucket.
    """

    # Absolute paths of common Code Ocean folders
    data_folder = Path(os.path.abspath("../data"))

    for d in data_folder.glob("*"):
        if d.is_dir():
            print(f"Data in {d}: {list(d.glob('*'))}")

    results_folder = Path(os.path.abspath("../results"))

    mode = str(sys.argv[1:])
    mode = mode.replace("[", "").replace("]", "").casefold()
    sys.argv = [sys.argv[0]]

    # Loading .env file
    # dotenv_path = Path(os.path.dirname(os.path.realpath(__file__))) / ".env"
    # load_env_file = load_dotenv(dotenv_path=dotenv_path)
    # logger.info(f"Load env file status: {load_env_file}")

    # Getting teams notification channel link
    alert_bot_link = os.environ["CUSTOM_KEY"]
    alert_configs = get_yaml_config(SCRIPT_DIR.joinpath("utils/alert_configs.yml"))

    logger.info(f"Alert bot link: {alert_bot_link}")
    logger.info(f"SES alert configs: {alert_configs}")

    # It is assumed that these files
    # will be in the data folder
    required_input_elements = [
        f"{data_folder}/processing_manifest.json",
        f"{data_folder}/input_aind_metadata/data_description.json",
    ]

    if "clean" in mode:
        required_input_elements = [
            f"{data_folder}/modified_processing_manifest.json",
            f"{data_folder}/input_aind_metadata/data_description.json",
        ]

    missing_files = utils.validate_capsule_inputs(required_input_elements)

    if len(missing_files):
        raise ValueError(
            f"We miss the following files in the capsule input: {missing_files}"
        )

    logger.info(f"Data in data folder: {os.listdir(data_folder)}")

    email_message_params = {}
    if "dispatch" in mode:
        pipeline_config, dataset_name, investigators = get_data_config(
            data_folder=data_folder,
            data_description_path="input_aind_metadata/data_description.json",
        )

        # Creating new metadata for stitched dataset
        output_dispatch_metadata, new_dataset_name = create_derived_stitched_metadata(
            data_folder=data_folder, results_folder=results_folder, logger=logger
        )

        # Looking for files
        flatfield_folder = data_folder.joinpath("flatfield_estimation")
        destripe_files = [str(p) for p in list(data_folder.glob("image_destriping_*"))]
        stitch_folder = data_folder.joinpath("stitched")
        fuse_folder = data_folder.joinpath("fused")
        ccf_folders = glob(f"{data_folder}/ccf_registration_results/ccf_*")

        bucket_path = "aind-open-data"
        s3_path = f"s3://{bucket_path}/{new_dataset_name}"
        dest_zarr_path = f"{s3_path}/image_tile_fusing/OMEZarr"

        # Getting S3 paths for channels
        s3_paths_for_channels = [
            f"{dest_zarr_path}/{fused_zarr.name}"
            for fused_zarr in fuse_folder.glob("*.zarr")
        ]

        axes_resolution = pipeline_config["pipeline_processing"]["stitching"][
            "resolution"
        ]
        output_json, ng_link_path = create_ng_link(
            config={
                "bucket_path": bucket_path,
                "output_folder": results_folder,
                "ng_base_url": "https://aind-neuroglancer-sauujisjxq-uw.a.run.app",
                "z_res": axes_resolution[2]["resolution"],
                "y_res": axes_resolution[1]["resolution"],
                "x_res": axes_resolution[0]["resolution"],
            },
            s3_channel_paths=s3_paths_for_channels,
            s3_dataset_path=s3_path,
        )

        email_message_params["ng_link_path"] = ng_link_path

        # Creating QC Metrics
        qc_evaluators = [
            {
                "name": "Neuroglancer Link Evaluation",
                "description": "Checks that the whole-brain neuroglancer link was created",
                "notes": "",
                "stage": "Processing",
                "qc_metric_values": [
                    {
                        "name": "Dataset neuroglancer link",
                        "description": "Qualitative check that the neuroglancer link was created",
                        "value": "",
                        "reference": ng_link_path,
                        "status": "Pending",
                    },
                ],
            },
        ]

        utils.create_quality_control_metadata(
            qc_eval_values=qc_evaluators,
            output_path=output_dispatch_metadata,
        )

        copy_intermediate_data(
            output_dispatch_metadata=output_dispatch_metadata,
            flatfield_folder=flatfield_folder,
            destripe_files=destripe_files,
            stitch_folder=stitch_folder,
            fuse_folder=fuse_folder,
            ccf_folders=ccf_folders,
            s3_path=s3_path,
            results_folder=results_folder,
            logger=logger,
        )

        data_results = glob(f"{results_folder}/*")
        logger.info(f"Data in {results_folder}: {data_results}")

        # Copying neuroglancer config out
        for out in utils.execute_command_helper(
            f"aws s3 cp {output_json} {s3_path}/{output_json.name}"
        ):
            logger.info(out)

        # Setting the stitching path in pipeline config
        pipeline_config["pipeline_processing"]["stitching"]["s3_path"] = s3_path

        dispatch(
            processing_manifest=pipeline_config,
            results_folder=results_folder,
            bucket=bucket_path,
        )

        utils.save_dict_as_json(
            f"{results_folder}/modified_processing_manifest.json",
            pipeline_config,
        )

    elif "clean" in mode:
        logger.info("Starting cleaning...")
        pipeline_config, dataset_name, investigators = get_data_config(
            data_folder=data_folder,
            data_description_path="input_aind_metadata/data_description.json",
            processing_manifest_path="modified_processing_manifest.json",
        )

        pipeline_config["name"] = dataset_name

        clean_up(
            processing_manifest=pipeline_config,
            data_folder=data_folder,
            results_folder=results_folder,
            alert_bot_link=alert_bot_link,
        )

    else:
        raise NotImplementedError(f"The mode {mode} has not been implemented")

    if investigators:
        # Sending email alert
        send_email_alerts(
            mode=mode,
            alert_configs=alert_configs,
            investigators=investigators,
            dataset_name=dataset_name,
            logger=logger,
            email_message_params=email_message_params,
            source_email="notifications@allenneuraldynamics.org",
        )


if __name__ == "__main__":
    run()
